##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1573949/public_html/resto.creativeacademyid.com/
    - /bin/cp -R .vscode $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R lib $DEPLOYPATH
    - /bin/cp -R scss $DEPLOYPATH
    /bin/cp index.html $DEPLOYPATH